export const options = {
    id: '', 
    title: '',
    name: '',
    birthYear: '',
    deathYear: '',
    shelves1: '',
    shelves2: '',
    downloadCount: '',
    subjects: '',
    mediaType: '',
    languages: '',
    formats1: '',
    formats2: '',
    formats3: '',
    formats4: '',
    formats5: '',
    formats6: '',
    formats7: '',
  };